In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

In [2]:
product = pd.read_excel(
    r"E:\CODING_ALL\Data Analytics\projrcts\RetailIQ\data\processed\product_catalog.xlsx",
    sheet_name="processed"
)

df = product.copy()

In [3]:
print("Dataset shape:", df.shape)
print("\nColumn names:")
print(df.columns.tolist())

print("\nDataset information:")
df.info()

display(df.head())

Dataset shape: (1175, 9)

Column names:
['product_id', 'product_name', 'product_category', 'product_subcategory', 'brand', 'supplier', 'unit_price', 'product_cost', 'product_rating']

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1175 entries, 0 to 1174
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1175 non-null   object
 1   product_name         1175 non-null   object
 2   product_category     1175 non-null   object
 3   product_subcategory  1175 non-null   object
 4   brand                1175 non-null   object
 5   supplier             1175 non-null   object
 6   unit_price           1175 non-null   float64
 7   product_cost         1175 non-null   float64
 8   product_rating       1175 non-null   float64
dtypes: float64(3), object(6)
memory usage: 82.7+ KB

,product_id,product_name,product_category,product_subcategory,brand,supplier,unit_price,product_cost,product_rating
0,PROD-000001,Apple Sharable bifurcated algorithm Smartphones,Electronics,Smartphones,Apple,Alibaba,686.90,474.06,4.3
1,PROD-000002,Google User-centric even-keeled encryption Sma...,Electronics,Smartphones,Google,Euro Logistics,978.26,519.66,2.9
2,PROD-000003,LG Face-to-face client-driven support Smartphones,Electronics,Smartphones,LG,Asian Manufacturing,275.51,185.48,3.9
3,PROD-000004,Sony Customer-focused systematic support Smart...,Electronics,Smartphones,Sony,Amazon Supply,1120.49,564.86,4.8
4,PROD-000005,OnePlus Quality-focused background parallelism...,Electronics,Smartphones,OnePlus,Direct Import,1282.18,695.54,2.9

In [4]:
df.columns = df.columns.str.strip()

print("Dataset shape:", df.shape)
print("\nData types:")
print(df.dtypes)

numeric_cols = [
    "unit_price",
    "product_cost",
    "product_rating"
]

for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

display(df[numeric_cols].describe().T)

Dataset shape: (1175, 9)

Data types:
product_id              object
product_name            object
product_category        object
product_subcategory     object
brand                   object
supplier                object
unit_price             float64
product_cost           float64
product_rating         float64
dtype: object

,count,mean,std,min,25%,50%,75%,max
unit_price,1175.0,245.524400,251.267683,6.31,74.710,165.42,311.295,1482.95
product_cost,1175.0,126.536826,150.131833,1.97,29.565,74.54,153.045,993.63
product_rating,1175.0,3.683064,0.698046,2.50,3.100,3.70,4.300,4.90

In [5]:
missing = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": (df.isnull().mean() * 100).round(2)
})

display(missing.sort_values("Missing_Percentage", ascending=False))

print("Exact duplicate rows:", df.duplicated().sum())
print("Missing product IDs:", df["product_id"].isna().sum())
print("Unique product IDs:", df["product_id"].nunique())
print("Duplicate product IDs:", df["product_id"].duplicated().sum())

                     Missing_Count  Missing_Percentage
product_id                       0                 0.0
product_name                     0                 0.0
product_category                 0                 0.0
product_subcategory              0                 0.0
brand                            0                 0.0
supplier                         0                 0.0
unit_price                       0                 0.0
product_cost                     0                 0.0
product_rating                   0                 0.0

Exact duplicate rows: 0
Missing product IDs: 0
Unique product IDs: 1175
Duplicate product IDs: 0

In [6]:
checks = {
    "Negative unit price": df["unit_price"] < 0,
    "Zero unit price": df["unit_price"] == 0,
    "Negative product cost": df["product_cost"] < 0,
    "Negative product rating": df["product_rating"] < 0,
    "Rating above 5": df["product_rating"] > 5
}

for issue, condition in checks.items():
    print(f"{issue}: {condition.sum()}")

Negative unit price: 0
Zero unit price: 0
Negative product cost: 0
Negative product rating: 0
Rating above 5: 0

In [7]:
categorical_cols = [
    "product_name",
    "product_category",
    "product_subcategory",
    "brand",
    "supplier"
]

for col in categorical_cols:
    print(f"\n--- {col} ---")
    print("Unique values:", df[col].nunique())
    print("Missing values:", df[col].isna().sum())
    print(df[col].value_counts(dropna=False).head(10))

--- product_name ---
Unique values: 1175
Missing values: 0
product_name
Apple Sharable bifurcated algorithm Smartphones                               1
Johnson & Johnson Automated explicit customer loyalty Thermometers            1
Philips Inverse bi-directional artificial intelligence First Aid              1
Pure Vitamin Enterprise-wide needs-based frame First Aid                      1
Johnson & Johnson Configurable intermediate portal First Aid                  1
Braun Configurable upward-trending interface First Aid                        1
Pure Vitamin Multi-layered multi-state flexibility Blood Pressure Monitors    1
Fitbit Proactive system-worthy methodology Blood Pressure Monitors            1
GNC Networked global contingency Blood Pressure Monitors                      1
Garmin Open-architected value-added intranet Blood Pressure Monitors          1
Name: count, dtype: int64

--- product_category ---
Unique values: 15
Missing values: 0
product_category
Sports & Outdoors         91
Books & Media             87
Health & Wellness         86
Beauty & Personal Care    83
Automotive                81
Office Supplies           80
Electronics               78
Home Appliances           78
Grocery                   78
Toys & Games              77
Name: count, dtype: int64

--- product_subcategory ---
Unique values: 117
Missing values: 0
product_subcategory
Storage             16
Furniture           16
Smartphones         15
Bags                15
Frozen Foods        15
Rings               15
Children's Books    15
Fiction             15
Yoga                15
Fragrances          15
Name: count, dtype: int64

--- brand ---
Unique values: 144
Missing values: 0
brand
Williams-Sonoma      19
Puma                 19
Adidas               18
The North Face       17
LG                   16
Samsung              16
Johnson & Johnson    14
Kiehl's              14
Castrol              14
Nike                 14
Name: count, dtype: int64

--- supplier ---
Unique values: 10
Missing values: 0
supplier
MultiSource              143
North American Supply    129
Amazon Supply            126
Domestic Producers       124
Direct Import            122
Euro Logistics           120
Pacific Trade            106
Global Trade             106
Asian Manufacturing      104
Alibaba                   95
Name: count, dtype: int64

In [8]:
df["price_cost_difference"] = df["unit_price"] - df["product_cost"]

print("Products priced below cost:",
      (df["price_cost_difference"] < 0).sum())

display(
    df.loc[
        df["price_cost_difference"] < 0,
        ["product_id", "product_name", "unit_price", "product_cost"]
    ].head(20)
)

Products priced below cost: 0

Empty DataFrame
Columns: [product_id, product_name, unit_price, product_cost]
Index: []

In [10]:
df.to_csv("cleaned_product.csv", index=False)
print("Done!")

Done!