In [ ]:
from google.colab import files

uploaded = files.upload()

Saving customer_master.xlsx to customer_master.xlsx
Saving dataset_statistics.xlsx to dataset_statistics.xlsx
Saving ecommerce_sales_customer_analytics_150k.xlsx to ecommerce_sales_customer_analytics_150k.xlsx
Saving order_items.xlsx to order_items.xlsx
Saving product_catalog.xlsx to product_catalog.xlsx

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
sales = pd.read_excel(
    "ecommerce_sales_customer_analytics_150k.xlsx", sheet_name="copy"
)

customers = pd.read_excel("customer_master.xlsx", sheet_name="copy")
products = pd.read_excel("product_catalog.xlsx", sheet_name="copy")
order_items = pd.read_excel("order_items.xlsx", sheet_name="copy")

In [9]:
print("Rows and columns:", sales.shape)
display(sales.head())
sales.info()

Rows and columns: (138116, 46)

,order_id,order_date,order_status,sales_channel,customer_id,customer_name,customer_age,gender,customer_segment,customer_type,...,discount_amount,tax_amount,shipping_cost,net_sales,product_cost,profit,profit_margin_percentage,customer_lifetime_value,is_repeat_customer,customer_order_count
0,ORD-301242,2023-11-06,Completed,Mobile App,CUST-003102,Jasmine Ryan,55,Male,Consumer,Loyal,...,477.89,61.07,12.03,945.40,588.33,345.04,36.50,12459.68,True,11
1,ORD-773460,2025-12-24,Completed,Website,CUST-003124,Scott Chase,26,Male,Premium,Loyal,...,1456.06,320.83,9.00,2018.41,2031.88,-22.47,-1.11,13032.48,True,11
2,ORD-449374,2021-07-05,Completed,Mobile App,CUST-012496,Marc Wheeler,69,Female,Premium,Loyal,...,97.30,29.79,13.05,468.35,257.73,197.57,42.18,6159.44,True,6
3,ORD-567636,2023-01-21,Completed,Social Media,CUST-023928,Jennifer Smith,65,Male,Consumer,Loyal,...,53.34,34.39,20.85,546.52,277.84,247.83,45.35,5638.30,True,7
4,ORD-820028,2022-05-13,Completed,Social Media,CUST-012730,Jessica Wang,34,Female,Consumer,Loyal,...,133.63,421.35,23.03,2785.27,1231.88,1530.36,54.94,13240.10,True,8

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 138116 entries, 0 to 138115
Data columns (total 46 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   order_id                  138116 non-null  object
 1   order_date                138116 non-null  datetime64[ns]
 2   order_status              138116 non-null  object
 3   sales_channel             138116 non-null  object
 4   customer_id               138116 non-null  object
 5   customer_name             138116 non-null  object
 6   customer_age              138116 non-null  int64
 7   gender                    138116 non-null  object
 8   customer_segment          138116 non-null  object
 9   customer_type             138116 non-null  object
 10  customer_city             138116 non-null  object
 11  customer_state            138116 non-null  object
 12  customer_country          138116 non-null  object
 13  region                    138116 non-null  object
 14  customer_postal_code      138116 non-null  int64
 15  payment_method            138116 non-null  object
 16  payment_status            138116 non-null  object
 17  currency                  138116 non-null  object
 18  shipping_method           138116 non-null  object
 19  warehouse                 138116 non-null  object
 20  delivery_days             113559 non-null  float64
 21  estimated_delivery_days   113559 non-null  float64
 22  delivery_status           138116 non-null  object
 23  return_status             9462 non-null    object
 24  return_reason             9462 non-null    object
 25  rating                    138116 non-null  int64
 26  customer_rating           113559 non-null  float64
 27  review_sentiment          113559 non-null  object
 28  customer_review           113559 non-null  object
 29  marketing_channel         138116 non-null  object
 30  campaign_name             54883 non-null   object
 31  coupon_code               27614 non-null   object
 32  loyalty_points_earned     138116 non-null  int64
 33  loyalty_points_redeemed   138116 non-null  int64
 34  quantity                  138116 non-null  int64
 35  gross_sales               138116 non-null  float64
 36  discount_amount           138116 non-null  float64
 37  tax_amount                138116 non-null  float64
 38  shipping_cost             138116 non-null  float64
 39  net_sales                 138116 non-null  float64
 40  product_cost              138116 non-null  float64
 41  profit                    138116 non-null  float64
 42  profit_margin_percentage  138116 non-null  float64
 43  customer_lifetime_value   138116 non-null  float64
 44  is_repeat_customer        138116 non-null  bool
 45  customer_order_count      138116 non-null  int64
dtypes: bool(1), datetime64[ns](1), float64(12), int64(7), object(25)
memory usage: 47.6+ MB

In [10]:
# Column names
print(sales.columns.tolist())

# Missing values in each column
missing = sales.isnull().sum()

missing_report = pd.DataFrame({
    "Missing_Count": missing,
    "Missing_Percentage": (missing / len(sales) * 100).round(2)
})

display(
    missing_report.sort_values(
        "Missing_Percentage", ascending=False
    )
)

# Exact duplicate rows
print("Duplicate rows:", sales.duplicated().sum())

# Summary of numerical columns
display(sales.describe().T)

['order_id', 'order_date', 'order_status', 'sales_channel', 'customer_id', 'customer_name', 'customer_age', 'gender', 'customer_segment', 'customer_type', 'customer_city', 'customer_state', 'customer_country', 'region', 'customer_postal_code', 'payment_method', 'payment_status', 'currency', 'shipping_method', 'warehouse', 'delivery_days', 'estimated_delivery_days', 'delivery_status', 'return_status', 'return_reason', 'rating ', 'customer_rating', 'review_sentiment', 'customer_review', 'marketing_channel', 'campaign_name', 'coupon_code', 'loyalty_points_earned', 'loyalty_points_redeemed', 'quantity', 'gross_sales', 'discount_amount', 'tax_amount', 'shipping_cost', 'net_sales', 'product_cost', 'profit', 'profit_margin_percentage', 'customer_lifetime_value', 'is_repeat_customer', 'customer_order_count']

                          Missing_Count  Missing_Percentage
return_status                    128654               93.15
return_reason                    128654               93.15
coupon_code                      110502               80.01
campaign_name                     83233               60.26
review_sentiment                  24557               17.78
customer_rating                   24557               17.78
estimated_delivery_days           24557               17.78
delivery_days                     24557               17.78
customer_review                   24557               17.78
order_id                              0                0.00
order_status                          0                0.00
sales_channel                         0                0.00
customer_id                           0                0.00
order_date                            0                0.00
region                                0                0.00
customer_country                      0                0.00
customer_state                        0                0.00
customer_city                         0                0.00
customer_type                         0                0.00
customer_segment                      0                0.00
gender                                0                0.00
customer_age                          0                0.00
customer_name                         0                0.00
warehouse                             0                0.00
shipping_method                       0                0.00
currency                              0                0.00
payment_method                        0                0.00
delivery_status                       0                0.00
payment_status                        0                0.00
customer_postal_code                  0                0.00
marketing_channel                     0                0.00
rating                                0                0.00
loyalty_points_earned                 0                0.00
loyalty_points_redeemed               0                0.00
quantity                              0                0.00
gross_sales                           0                0.00
discount_amount                       0                0.00
tax_amount                            0                0.00
shipping_cost                         0                0.00
net_sales                             0                0.00
product_cost                          0                0.00
profit                                0                0.00
profit_margin_percentage              0                0.00
customer_lifetime_value               0                0.00
is_repeat_customer                    0                0.00
customer_order_count                  0                0.00

Duplicate rows: 0

,count,mean,min,25%,50%,75%,max,std
order_date,138116,2023-07-21 10:11:31.662081280,2021-01-01 00:00:00,2022-04-20 00:00:00,2023-08-01 00:00:00,2024-10-29 00:00:00,2025-12-31 00:00:00,NaN
customer_age,138116.0,45.862681,18.0,32.0,46.0,60.0,74.0,16.467676
customer_postal_code,138116.0,50210.88931,516.0,25509.0,50183.0,74898.0,99950.0,28569.767779
delivery_days,113559.0,4.557772,0.0,2.0,4.0,7.0,14.0,2.810012
estimated_delivery_days,113559.0,4.298875,0.0,2.0,4.0,6.0,10.0,2.59408
rating,138116.0,3.068486,0.0,3.0,4.0,4.0,5.0,1.514408
customer_rating,113559.0,3.677015,1.6,3.4,3.7,4.0,5.0,0.483672
loyalty_points_earned,138116.0,103.991051,0.0,17.0,70.0,151.0,1621.0,115.17564
loyalty_points_redeemed,138116.0,51.934128,0.0,3.0,25.0,71.0,1063.0,73.217692
quantity,138116.0,5.615244,1.0,3.0,5.0,8.0,24.0,3.371289
gross_sales,138116.0,1375.384176,6.31,458.92,995.73,1871.2,16051.19,1291.009554
discount_amount,138116.0,237.621614,0.0,26.3275,103.285,277.125,6759.02,378.779459
tax_amount,138116.0,122.462933,0.34,34.65,77.01,156.2,2091.52,140.939368
shipping_cost,138116.0,22.27808,0.0,9.82,19.19,30.75,149.52,16.022739
net_sales,138116.0,1282.503575,5.8,448.2,950.76,1744.5825,16218.0,1169.274669
product_cost,138116.0,708.903449,1.97,207.6675,478.955,953.7625,9963.41,730.04497
profit,138116.0,551.322046,-1281.59,190.7575,408.395,752.845,7083.68,516.300936
profit_margin_percentage,138116.0,45.065997,-59.55,38.88,46.99,53.77,77.59,13.120357
customer_lifetime_value,138116.0,8971.639047,22.55,5713.57,8392.525,11651.03,30268.44,4430.506588
customer_order_count,138116.0,6.990559,1.0,5.0,7.0,9.0,20.0,2.444166

In [18]:
for col in ["quantity", "discount_amount", "profit"]:
    if col in sales.columns:
        print(f"\n{col}")
        print(sales[col].describe())

quantity
count    138116.000000
mean          5.615244
std           3.371289
min           1.000000
25%           3.000000
50%           5.000000
75%           8.000000
max          24.000000
Name: quantity, dtype: float64

discount_amount
count    138116.000000
mean        237.621614
std         378.779459
min           0.000000
25%          26.327500
50%         103.285000
75%         277.125000
max        6759.020000
Name: discount_amount, dtype: float64

profit
count    138116.000000
mean        551.322046
std         516.300936
min       -1281.590000
25%         190.757500
50%         408.395000
75%         752.845000
max        7083.680000
Name: profit, dtype: float64

In [27]:
checks = {
    "Invalid customer age": (
        (sales["customer_age"] < 0) |
        (sales["customer_age"] > 120)
    ),
    "Non-positive quantity": sales["quantity"] <= 0,
    "Negative discount": sales["discount_amount"] < 0,
    "Negative gross sales": sales["gross_sales"] < 0,
    "Negative shipping cost": sales["shipping_cost"] < 0,
    "Negative product cost": sales["product_cost"] < 0,
}

for name, condition in checks.items():
    print(f"{name}: {condition.sum()} records")

Invalid customer age: 0 records
Non-positive quantity: 0 records
Negative discount: 0 records
Negative gross sales: 0 records
Negative shipping cost: 0 records
Negative product cost: 0 records

In [30]:
losses = sales[sales["profit"] < 0]

print("Loss-making records:", len(losses))
print("Percentage:", round(len(losses) / len(sales) * 100, 2), "%")

display(
    losses.nsmallest(10, "profit")[
        [
            "order_id",
            "order_date",
            "quantity",
            "gross_sales",
            "discount_amount",
            "tax_amount",
            "shipping_cost",
            "net_sales",
            "product_cost",
            "profit",
            "profit_margin_percentage"
        ]
    ]
)

Loss-making records: 1296
Percentage: 0.94 %

,order_id,order_date,quantity,gross_sales,discount_amount,tax_amount,shipping_cost,net_sales,product_cost,profit,profit_margin_percentage
61475,ORD-750525,2021-11-04,10,8489.07,4748.59,374.05,28.23,4142.76,5396.12,-1281.59,-30.94
86346,ORD-556742,2021-12-08,5,5738.55,3443.13,229.54,5.61,2530.57,3754.45,-1229.49,-48.59
50698,ORD-780785,2021-11-13,5,6311.95,3787.17,126.24,4.57,2655.59,3856.85,-1205.83,-45.41
113495,ORD-480427,2024-12-15,10,7313.37,3916.52,237.78,33.53,3668.16,4806.76,-1172.13,-31.95
106034,ORD-550155,2023-12-18,19,7750.94,4201.89,248.44,27.92,3825.41,4961.41,-1163.92,-30.43
70536,ORD-817113,2024-12-19,8,5190.31,3024.82,151.59,36.01,2353.09,3413.09,-1096.01,-46.58
82973,ORD-415091,2023-11-19,8,5870.88,3273.17,181.84,3.57,2783.12,3831.12,-1051.57,-37.78
106709,ORD-683198,2022-12-08,17,8019.24,4689.05,333.03,20.45,3683.67,4714.71,-1051.49,-28.54
32897,ORD-260655,2022-11-18,10,5689.23,3273.89,314.00,22.10,2751.44,3763.63,-1034.29,-37.59
121227,ORD-420869,2023-11-05,11,5851.55,3269.32,180.76,42.42,2805.41,3794.99,-1032.00,-36.79

In [32]:
sales["expected_net_sales"] = (
    sales["gross_sales"]
    - sales["discount_amount"]
    + sales["tax_amount"]
    + sales["shipping_cost"]
)

sales["net_sales_difference"] = (
    sales["net_sales"] - sales["expected_net_sales"]
)

display(
    sales.loc[
        sales["net_sales_difference"].abs() > 0.02,
        [
            "gross_sales",
            "discount_amount",
            "tax_amount",
            "net_sales",
            "expected_net_sales",
            "net_sales_difference"
        ]
    ].head(20)
)

Empty DataFrame
Columns: [gross_sales, discount_amount, tax_amount, net_sales, expected_net_sales, net_sales_difference]
Index: []

In [33]:
# Delivery days should not normally be negative
if "delivery_days" in sales.columns:
    invalid_delivery = sales["delivery_days"] < 0

    print("Negative delivery days:", invalid_delivery.sum())

    display(
        sales.loc[
            invalid_delivery,
            ["order_id", "order_status",
             "delivery_status", "delivery_days"]
        ].head(20)
    )

Negative delivery days: 0

Empty DataFrame
Columns: [order_id, order_status, delivery_status, delivery_days]
Index: []

In [36]:
# Rating values outside the expected 1–5 range
if "rating" in sales.columns:
    invalid_rating = (
        sales["rating"].notna()
        & ~sales["rating"].between(1, 5)
    )
    print("Suspicious ratings:", invalid_rating.sum())

# Discount percentage check, if the column exists
if "discount_amount" in sales.columns:
    invalid_discount = ~((sales["discount_amount"]/sales["gross_sales"])*100).between(0, 100)

    print("Invalid discount percentages:", invalid_discount.sum())

Suspicious ratings: 24557
Invalid discount percentages: 0

In [37]:
display(
    sales[
        ["customer_id", "is_repeat_customer",
         "customer_order_count"]
    ].head(20)
)

print(
    sales["is_repeat_customer"]
    .value_counts(dropna=False)
)

print(
    sales["customer_order_count"]
    .describe()
)

    customer_id  is_repeat_customer  customer_order_count
0   CUST-003102                True                    11
1   CUST-003124                True                    11
2   CUST-012496                True                     6
3   CUST-023928                True                     7
4   CUST-012730                True                     8
5   CUST-021468                True                     3
6   CUST-023734                True                     4
7   CUST-020081                True                     7
8   CUST-011921                True                    10
9   CUST-016600                True                     7
10  CUST-021779                True                     8
11  CUST-013168                True                     5
12  CUST-002075                True                     5
13  CUST-018476                True                     9
14  CUST-012765                True                     7
15  CUST-001436                True                     8
16  CUST-000109                True                     6
17  CUST-022079                True                    11
18  CUST-000860                True                     4
19  CUST-012835                True                     6

is_repeat_customer
True     137782
False       334
Name: count, dtype: int64
count    138116.000000
mean          6.990559
std           2.444166
min           1.000000
25%           5.000000
50%           7.000000
75%           9.000000
max          20.000000
Name: customer_order_count, dtype: float64

In [1]:
sales_clean = sales.copy()

sales_clean.to_csv(
    "sales_cleaned.csv",
    index=False
)

NameError: name 'sales' is not defined